name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: '6.0' 

    - name: Build and publish .NET Core application
      run: |
        dotnet restore CesarAPI/CesarAPI.csproj
        dotnet publish -c Release -o CesarAPI/publish CesarAPI/CesarAPI.csproj

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: Deployment_yml  
        folder: CesarAPI/publish 
        token: ${{ secrets.GH_SECRET }}
        clean: true
