name: Build and deploy ASP.Net Core app to Azure Web App - spaceshooter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: |
          cd CesarAPI  # Navigera till din projektmapp
          dotnet build --configuration Release

      - name: dotnet publish
        run: |
          cd CesarAPI  # Se till att du är i rätt mapp
          dotnet publish -c Release -o ./publish  # Publicera till ./publish-katalogen

      - name: List directory for debugging
        run: |
          ls -al ./CesarAPI/publish  # Lista innehållet för att se om katalogen finns

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./CesarAPI/publish  # Path till den publicerade applikationen

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'spaceshooter'
          slot-name: 'Production'
          package: './CesarAPI/publish'  # Path till den publicerade mappen
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FBDF5DD8B29D4D2BAD1453F292421EE3 }}
