name: Build and deploy ASP.Net Core app to Azure Web App - spaceshooter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: |
          cd CesarAPI  # Navigera till din projektmapp
          dotnet build --configuration Release

      - name: dotnet publish
        run: |
          cd CesarAPI  # Se till att vi är i rätt mapp
          dotnet publish -c Release -o ./publish  # Publicera till ./publish-katalogen

      - name: Zip the published files
        run: |
          cd CesarAPI/publish
          zip -r ../publish.zip .  # Skapa en zip-fil av publiceringsfilerna

      - name: List directory after zipping
        run: |
          ls -al ./CesarAPI  # Kontrollera om publish.zip existerar

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./CesarAPI/publish.zip  # Path till zip-filen

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: List downloaded files
        run: |
          ls -al .  # Lista filerna i den nedladdade artefakten för att verifiera

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'spaceshooter'
          slot-name: 'Production'
          package: './CesarAPI/publish.zip'  # Path till zip-filen
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FBDF5DD8B29D4D2BAD1453F292421EE3 }}
