name: .NET Core CI

on:
  push:
    branches:
    - 'Developer'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' 

    - name: Restore dependencies
      run: dotnet restore xUnitTests/xUnitTests.csproj

    - name: Build
      run: |
        cd xUnitTests
        dotnet build --configuration Release --no-restore

    - name: Test
      run: |
        cd xUnitTests
        dotnet test --no-build --verbosity normal
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
